Capstone Project - The Battle of the Neighborhoods 

Applied Data Science Capstone by IBM/Coursera

Table of contents
•Introduction: Business Problem
•Data
•Methodology
•Analysis
•Results and Discussion
•Conclusion

Introduction: Business Problem

 Shanghai is the economic center of China and has a population of over 14 million people. As a developed city, Shanghai is blessed with 19 metro lines and 413 stations. 
  As a newly born city, millions of people come in and out from Shanghai in one year. When people look for suitable house to rent or buy, places near a metro station are prone to be more attractive. The aim of this project is to look at the kinds of venues surrounding the metro stations and classify them based on the types of venues near a station the most, as well as taking into consideratio the geographic location of the station. The target customer of this project is the one who searches for a new home and wants to get well-knowed about one area.

Data

The final dataframe used for data analysis contains the line 1 of Shanghai's metro stations' data. The list of all the metro stations we used were retrieved from the Wikipedia page:https://wanweibaike.com/wiki-%E4%B8%8A%E6%B5%B7%E5%9C%B0%E9%93%81%E7%AB%99%E7%82%B9%E5%88%97%E8%A1%A8#1号线 The dataframe which was retrieved through URL is concise and there is no need to molify the content. So the next step of this project is to coordinate the latitude and longitude to each row, by looping through the whole list and creating custom Google Geocoding API queries for each row from their cell values. We then save the dataframe into a .csv file, so that we can use it for repeated testing and data classification, without having to call the Google API each time.Using the coordinates we got from querying with the Google API, we can query locations and any nearby venues with the Foursquare Places API. We query each station's location and collect the number of venues, sorted by the top-level categories available from the Foursquare API. We can then classify each station based on the top categories of the total number of nearby venues around a station. Clusters of station locations and their surrounding areas can then be marked on a map of Shanghai and inform users about that part of the city.

Retrieve Shanghai metro stations' information from Wikipedia:

In [1]:
import pandas as pd
import csv
for i in range(1,2):
    url='https://wanweibaike.com/wiki-%E4%B8%8A%E6%B5%B7%E5%9C%B0%E9%93%81%E7%AB%99%E7%82%B9%E5%88%97%E8%A1%A8#1号线'
    tb=pd.read_html(url)[0]
    tb.to_csv(r'SH.csv', mode='a', encoding='utf_8_sig', header=1, index=0)
    print('第'+str(i)+'页抓取完成')

第1页抓取完成

Take a look at the data using the code below :

In [2]:
import pandas as pd
import numpy as np
raw_df=pd.read_csv(r'SH.csv')
raw_df.head()

,Number,Station_Name,Opened,Location,Platform_Level,Platform_Type,Transfers
0,1,莘庄,1996年12月28日,Minhang,At-grade,Side platform,5
1,1,外环路,1996年12月28日,Minhang,At-grade,Side platform,NaN
2,1,莲花路,1996年12月28日,Minhang,At-grade,Side platform,NaN
3,1,锦江乐园,1996年12月28日,Xuhui,At-grade,Side platform,NaN
4,1,上海南站,2004年10月30日,Xuhui,Underground,Island platform,3

We want to get the longitude and latitude from the Baidu API (http://api.map.baidu.com/place/v2/search?query=#geocoding) and we will use the json outputFormat with the address and components filtering parameters, with our API key being the last ingredient in the query.For the components part, we use the administrative_area:Shanghai to help narrow down the search to just the Shanghai administrative area in China. The output from the query will be a csv text.

In [3]:
import pandas
from bs4 import BeautifulSoup 
from urllib import request
import re
import pandas as pd
import numpy as np
import urllib.parse as urp
from xml.etree import ElementTree
import time

def __get_location1__(name,city):  
        my_ak = '54sYa6LO9aMKWOdyzaQfRkIGc3eD31Qa'    
        tag = urp.quote('地铁站')
        qurey = urp.quote(name)
        try:
            url = 'http://api.map.baidu.com/place/v2/search?query='+qurey+'&tag='+'&region='+urp.quote(city)+'&output=json&ak='+my_ak
            print(url)
            req = request.urlopen(url)
            res = req.read().decode()
            lat = pd.to_numeric(re.findall('"lat":(.*)',res)[0].split(',')[0])
            lng = pd.to_numeric(re.findall('"lng":(.*)',res)[0])
            return (lng,lat)
        except:
            return 0,0

Let's combine the latitude and longitude with the dataframe：

In [4]:
Station=pd.read_csv(r'Station.csv',encoding='gb18030')
Station.head()
Station.head()latitudes=[]
longitudes=[]
for i in Stations:
    __get_location1__(i,'上海')
    latitudes.append(lat)
    longitudes.append(lng)

  Station_Name
0           莘庄
1          外环路
2          莲花路
3         锦江乐园
4         上海南站

In [5]:
import pandas as pd
df=pd.read_csv(r'SH_1.csv')
df

,Number,Station_Name,Opened,Location,Platform_Level,Platform_Type,Transfers,Longitude,Latitude
0,1,莘庄,1996年12月28日,Minhang,At-grade,Side platform,5,121.392186,31.116872
1,1,外环路,1996年12月28日,Minhang,At-grade,Side platform,NaN,121.399614,31.126649
2,1,莲花路,1996年12月28日,Minhang,At-grade,Side platform,NaN,121.409334,31.136734
3,1,锦江乐园,1996年12月28日,Xuhui,At-grade,Side platform,NaN,121.415479,31.145542
4,1,上海南站,2004年10月30日,Xuhui,Underground,Island platform,3,121.435865,31.159439
5,1,漕宝路,1993年5月28日,Xuhui,Underground,Island platform,12,121.440466,31.174838
6,1,上海体育馆,1993年5月28日,Xuhui,Underground,Island platform,4,121.443398,31.188813
7,1,徐家汇,1993年5月28日,Xuhui,Underground,Island platform,9+11,121.443395,31.194557
8,1,衡山路,1995年4月10日,Xuhui,Underground,Island platform,NaN,121.448545,31.205096
9,1,常熟路,1995年4月10日,Xuhui,Underground,Island platform,7,121.456663,31.219862
10,1,陕西南路,1995年4月10日,Huangpu,Underground,Island platform,10+12,121.465616,31.222063
11,1,黄陂南路,1995年4月10日,Huangpu,Underground,Island platform,NaN,121.479748,31.228732
12,1,人民广场,1995年4月10日,Huangpu,Underground,Island platform[注 3],2+8,121.481099,31.238688
13,1,新闸路,1995年4月10日,Huangpu,Underground,Island platform,NaN,121.466564,31.241872
14,1,汉中路,1995年4月10日,Jing'an,Underground,Island platform,12+13,121.465207,31.247233
15,1,上海火车站,1995年4月10日,Jing'an,Underground,Island platform,2+4,121.462056,31.255923
16,1,中山北路,2004年12月28日,Jing'an,Underground,Island platform,NaN,121.465657,31.264959
17,1,延长路,2004年12月28日,Jing'an,Underground,Island platform,NaN,121.461892,31.278061
18,1,上海马戏城,2004年12月28日,Jing'an,Underground,Island platform,NaN,121.458503,31.285845
19,1,汶水路,2004年12月28日,Jing'an,Elevated,Side platform,NaN,121.456541,31.298974
20,1,彭浦新村,2004年12月28日,Jing'an,Elevated,Side platform,NaN,121.455097,31.312943
21,1,共康路,2004年12月28日,Jing'an,Elevated,Side platform,NaN,121.453467,31.325349
22,1,通河新村,2004年12月28日,Baoshan,Elevated,Side platform,NaN,121.447965,31.337451
23,1,呼兰路,2004年12月28日,Baoshan,Elevated,Side platform,NaN,121.444156,31.346106
24,1,共富新村,2004年12月28日,Baoshan,Elevated,Side platform,NaN,121.440526,31.361410
25,1,宝安公路,2007年12月29日,Baoshan,Elevated,Side platform,NaN,121.132161,31.153121
26,1,友谊西路,2007年12月29日,Baoshan,Elevated,Side platform,NaN,121.434421,31.387459
27,1,富锦路,2007年12月29日,Baoshan,Elevated,Side platform,NaN,121.431087,31.398542